name: Go Linter
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  golangci:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          only-new-issues: true
